name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        environment: ["py311", "py312", "py313"]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.0
        with:
          environments: ${{ matrix.environment }}

      - name: Run tests
        run: pixi run -e ${{ matrix.environment }} test

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
